create edit password functionality
GSG-G11/Wasslni pull request #54
Opened 2022-04-22 16:10 UTC by MontherIsmail

Relates #50
what route should do
-edit password for buyer and seller

-method: POST

-Route: /api/v1/profile/

Protected: Yes

Required middleWares: asyncMiddleware, checkAuth
Response
Successs  : status : 201, {message : password edited } .
Failure : status : 401 ,  {message : validation fails} . // validation fails
Failure : status : 400 ,  {message : enter new password} . // same old password
Failure : status 500 , {message : internal server error } //server error
Request body: if exists
{
newPassword

}

        : is exists
{
  password: string().required()
}

Tests:
 all our status code
 201 => insert in data base 
401 => validation fails
400 =>bad request
503  =>service unavailable
500 => server error

2022-04-22 16:11 UTC, Fady-Alwazir approved these changes

2022-04-22 19:44 UTC, mayar-kabaja approved these changes

2022-04-22 19:59 UTC, WessalJawad95 approved these changes

2022-04-22 20:15 UTC, Nizar7zak requested changes

2022-04-22 20:15 UTC, Nizar7zak commented on server/src/controllers/profile/editPassword.ts
> +  const id = 1;
I suppose you forgot get userId from request, not as static data !

2022-04-22 20:15 UTC, Nizar7zak commented on server/src/controllers/profile/editPassword.ts
> +  const hashedNewPassword = await hashPassword(newPassword);
here, you should check if the old password equal new password, then you will send a response to tell the client side your new password matching your old password.

2022-04-22 23:21 UTC, Fady-Alwazir approved these changes

2022-04-23 00:58 UTC, Nizar7zak approved these changes
Good job Monther.

2022-04-23 01:02 UTC, Nizar7zak requested changes

2022-04-23 01:02 UTC, Nizar7zak commented on server/src/controllers/profile/editPassword.ts
> +  const { id } = req;
from checkAuth middleware we take a userId not id here.

2022-04-23 11:05 UTC, merged