51 edit profile info
GSG-G11/Wasslni pull request #55
Opened 2022-04-22 16:38 UTC by Fady-Alwazir

2022-04-22 19:45 UTC, mayar-kabaja approved these changes

2022-04-22 20:19 UTC, Nizar7zak requested changes
Great Job Fadi.

2022-04-22 20:19 UTC, Nizar7zak commented on server/src/controllers/profile/editProfile.ts
> +  if (!edited) {
can you express more how the rowCount can be falsy value?
here we set update to our table not get an exist data.

2022-04-22 21:26 UTC, MontherIsmail approved these changes

2022-04-23 00:59 UTC, Nizar7zak approved these changes

2022-04-23 02:29 UTC, merged